### ISSUE TITLE
Code completion stops working after a while

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#117]
Not much information on this, but after about an hour of use Crane stops showing me any suggestions for my project.

**Comment by TheColorRed** [comment]
I have had this issue while developing the plugin. Could it be that javascript is doing garbage collection and clearing the data? If this is the case, whenever saving a file, an empty cache will be saved, then the next time the cache is loaded it won't have any suggestions. You will then need to reindex your files.

**Comment by nevadascout** [comment]
That makes perfect sense. A re-index of the files does indeed sort the issue.

Maybe we need to prevent saving the cache if the tree is an empty object (or similar)?

**Comment by TheColorRed** [comment]
From my little bit of reading, when something becomes inaccessible it gets cleaned up.

1. A distinguished set of objects are assumed to be reachable: these are known as the roots. Typically, these include all the objects referenced from anywhere in the call stack (that is, all local variables and parameters in the functions currently being invoked), and any global variables.
1. **Objects are kept in memory while they are accessible from roots through a reference or a chain of references.**

Source: http://javascript.info/tutorial/memory-leaks

Would placing the tree on the window object make it less likely to get cleaned? `window.workspaceTree`

**Comment by nevadascout** [comment]
Might be worth trying

**Comment by nevadascout** [comment]
Adding the tree to the `window` object didn't seem to work, so _(and yes, this is hacky)_ I've added a timer that fires every 15 seconds to access the "essential" objects to try to avoid garbage collection.

Haven't fully tested this, but hopefully it will prevent them being collected during periods of inactivity.

```ts
// Prevent garbage collection of essential objects
let timer = setInterval(() => {
                treeBuilder.Ping();
                return workspaceTree.length;
            }, 15000);
```

The `workspaceTree` is the main object that we need, but hanging onto the `treeBuilder` as well can't be a bad thing.
