### ISSUE TITLE
Missing code completition for mssql functions

### ISSUE THREAD

**Issue by StefanoPernat** [HvyIndustries/crane#121]
Hello,
your plugin is awesome but code completition is missing for every mssql_ functions.

Regards
Stefano

**Comment by TheColorRed** [comment]
A.) Did you download the php stubs? <kbd>F1</kbd> `Crane - Download PHP Library Stubs`
B.) You probably shouldn't be using that mysql library as it isn't supported in mysql any more.

**Comment by StefanoPernat** [comment]
Yes I know that right now is deprecated but I have to maintain an old project and not have time to switch to PDO or any ORM library.

Thanks for your reply
