### ISSUE TITLE
Parsing never completes

### ISSUE THREAD

**Issue by berkzorlu** [HvyIndustries/crane#130]
I haven't been able to get the parsing to finish yet. I have 11,000+ files, but it's stopping on the 100th file (0.9%). When debugmode is enabled, here is the error I'm getting:

[ERROR] There was a problem parsing PHP file: c:...\blah.php
[ERROR] [TypeError: Cannot read property '0' of null]

And it's probably worth noting that it gives that error twice - it first gives it for the 90th file, but somehow continues and stops at the 100th with the same error.

**Comment by nevadascout** [comment]
Hey, thanks for reporting this and I'm sorry this is causing you an issue.

To solve this issue, I need to know what code is causing the parser to break. Are you able to share the source code of the file that is having a problem with me?

**Comment by berkzorlu** [comment]
I'm not able to share any of the code since it's my company's property. Are
you able to release a more detailed debug message including the line number
so I modify and send you the code related to that line?

**Comment by nevadascout** [comment]
This should be fixed with the update of the `php-parser` library in v0.3.0

**Comment by nevadascout** [comment]
Fixed in v0.3.0
