### ISSUE TITLE
Not indexing WordPress files

### ISSUE THREAD

**Issue by hadi77ir** [HvyIndustries/crane#132]
It is not WordPress-compliant, for example when we are developing plugins or making themes its dictionary doesn't have any of WordPress functions.

**Comment by TheColorRed** [comment]
I don't know much about wordpress, but do any of these files have HTML in them?

**Comment by nevadascout** [comment]
If there are top level (global) functions declared in other files, they won't be suggested in the file that you're working in. This is being changed in a future release.

**Comment by tanc** [comment]
This appears to be the case for Drupal 7 too. Drupal 7 uses procedural code and it seems as if this extension doesn't pick it up for suggestions in the current file.

**Comment by nevadascout** [comment]
Duplicate of #148 (added Drupal to the list too)
