### ISSUE TITLE
Migrate to Language Server Protocol version 2.x

### ISSUE THREAD

**Issue by kaloyan-raev** [HvyIndustries/crane#138]
I am experimenting with integrating the Crane language server in Eclipse Che. 

Eclipse Che implements the VSCode Language Server Protocol, which allows integrating any language server. However, Eclipse Che implements version 2 of the protocol, while Crane - version 1.

I need Crane to migrate to version 2 of the language server protocol. I will push a PR soon.

**Comment by nevadascout** [comment]
Merged in #139
