### ISSUE TITLE
Parser crash during parse of TCPDF library

### ISSUE THREAD

**Issue by pablopunk** [HvyIndustries/crane#144]
So, I have a fairly large PHP project (half _symfony2_ and half raw php) and when I install this extension it always starts to index files very fast but **it stops at 32.6%**, like there was a huge file or something, but it never seems to continue.

<img width="263" alt="screen shot 2016-09-02 at 10 24 29 am" src="https://cloud.githubusercontent.com/assets/4324982/18207061/79c69cd2-70f7-11e6-87a3-12f61ccf4d22.png">

_I'm on MacOS 10.12 with PHP 5.6_

_UPDATE:_ I enabled **debug mode** and it seems to stop at this file:

<img width="790" alt="ss" src="https://cloud.githubusercontent.com/assets/4324982/18351395/075026f4-75a8-11e6-958c-943944fbf809.png">

**Comment by pablopunk** [comment]
Ok it seems I'm not the only one with this problem (see https://github.com/HvyIndustries/crane/issues/135).

Is there any way to configure *crane* to ignore `lib/PHPExcel`?

**Comment by smbkr** [comment]
I get the same issue on a large project (2992 files). The file in particular it's dying on for me is vendor/sendgrid/sendgrid-php/sendgrid-php.php, content of which is only:

`<?php
require 'vendor/autoload.php';
require 'lib/SendGrid.php';
?>`

So I don't think it's an issue with parsing the file. The file itself uses UTF-8 encoding, the only 'unusual' thing is that there is no new-line at EOF, but I know for a fact there's many other files like that in this project.

**Comment by pablopunk** [comment]
Yep, it's weird. What I did now is:

- I deleted symfony folder `lib` from my project (`rm -rf lib`) cause there were more folders there triggering the error.
- Index all files successfully
- `git checkout lib` for getting the folder back into my project

Obviously this is not a fix, it's just a workaround for getting it to finish the indexing.

**Comment by Angelinsky7** [comment]
Same issue here, with a symfony project (the tuto project) on Windows 10.
The crash occurs on differents files (not always the same percentage) and the only way to retry is to reboot vscode.

**Comment by pablopunk** [comment]
I changed the title cause the error seems to happen with the folders of a symfony project.

**Comment by nevadascout** [comment]
@pablopunk I've been doing some work on stability and trying to improve the parser over the last few days as you can see here #148.

I've identified an issue (#154) with the latest version of Symfony in that the parser doesn't understand the PHP7 syntax in the `NullableController` test fixture.

This does seem to be unrelated to the issue that you are having, but I now recognise the error (`Cannot read property '3' of undefined`) and I believe I may have fixed this for the 0.2.1 release.

In any case, I'll download the PHPExcel library and test the latest version of the parser on it to see if I can reproduce this error.

**Comment by nevadascout** [comment]
After futher investigation it appears this is related to #157 (memory leak during parsing large files)

**Comment by pablopunk** [comment]
I'm still getting this error. I think it's related to [this issue](https://github.com/HvyIndustries/crane/issues/178).

[This feature](https://github.com/HvyIndustries/crane/issues/77) would be a great solution at least for now.

**Comment by nevadascout** [comment]
This should be fixed with the update of php-parser to 2.0.0

**Comment by nevadascout** [comment]
Released in v0.3.0
