### ISSUE TITLE
Lexical error reject() error

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#159]
Not sure what to make of this, @ichiriac any ideas?

This seems to be because the variable is called `$object` _(is that a PHP reserved keyword?)_, as when I renamed the variable to `$test123` the error stopped happening.

```
[Error: Lexical error on line 45. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).
...  protected static $οbject = array(    
-----------------------^]
Issue processing e:\php-frameworks\yii-advanced-2.0.9\vendor\fzaninotto\faker\src\Faker\Provider\el_GR\Company.php
```

_Framework: **Yii 2.0.9**_

**Comment by ichiriac** [comment]
@nevadascout thanks for the patch :+1:, it's merged and i've rebuild the lexer
