### ISSUE TITLE
Rename plugin on vscode marketplace

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#164]
Rename Crane from `Crane - PHP Intellisense` to `PHP Intellisense (Crane)` for better rankings when searching the marketplace

Also add `php` tag if not already

**Comment by TheColorRed** [comment]
What about a php image icon as well? That could also help it stick out in the marketplace as a php plugin.

**Comment by nevadascout** [comment]
Good idea. I'll whip something up...

**Comment by TheColorRed** [comment]
Does that work on a dark background?
