### ISSUE TITLE
Add "what's new" section to readme.md

### ISSUE THREAD

**Issue by leomeloxp** [HvyIndustries/crane#171]
Hi,

I just updated this module to its latest version on my VSCode and I couldn't see what has changed. Would it be possible to add a **Changelog** section to your readme.md so that we can see what's new from within VSCode when a new version lands?

Thanks 🙂

**Comment by lisurc** [comment]
I was looking too for the changelog. If I can add to this suggestion, a simple link to the "latest release" in the readme.md file would be enough in my case: https://github.com/HvyIndustries/crane/releases/latest

**Comment by TheColorRed** [comment]
All of the affected Items can be found here:

https://github.com/HvyIndustries/crane/issues?q=milestone%3A0.2.1+is%3Aclosed

**Comment by leomeloxp** [comment]
I think it's more of adding a link (or the changes) onto the readme as it gets displayed within VSCode, so we can see what has changed without having to leave the editor (or at least no more than 1 click away). 🙂

**Comment by TheColorRed** [comment]
Adding it to the readme I think would be a great idea.

**Comment by nevadascout** [comment]
Added in release v0.2.2
