### ISSUE TITLE
Index past 100%

### ISSUE THREAD

**Issue by TheColorRed** [HvyIndustries/crane#175]
Here is what I noticed:
1. Download Stubs
2. Re-index

At one point the indexer got to ~ 35%, then started over. It then indexed past 100%. I am not sure if just didn't reset the `numFilesProcessed` when it started over, but it did complete.

![index too many files](https://cloud.githubusercontent.com/assets/1571806/19122273/550bdc88-8aef-11e6-997d-66f2e221c101.PNG)

**Comment by nevadascout** [comment]
Interesting. Is there a reliable way to reproduce this?

**Comment by TheColorRed** [comment]
I am not sure, it unexpectedly happened to me once. I haven't seen it happen again, so I have no idea what I did.
