### ISSUE TITLE
Indexing stuck at 33% (240/743)

### ISSUE THREAD

**Issue by jendabek** [HvyIndustries/crane#178]
Sometimes earlier but it just never finish the indexing.
Indexed project is based on Codeigniter framework.

**Comment by dngsdk** [comment]
Same here. For me, it stops at 98% and never finishes. Using Laravel

**Comment by michalhudecek** [comment]
For me it stops at 29.1%. It started to happen after I imported libraries via composer install. Here are the libraries in composer.json. Is there any overlap with @dngsdk and @jendabek ?

	"require": {
		"php": ">= 5.3.1",
		"nette/nette": "2.3.10",
		"kdyby/facebook": "^2.0",
		"jublonet/codebird-php": "^3.1",
		"kdyby/nette-session-panel": "^3.2",
		"kdyby/curl": "~2.2",
		"djchen/pocket-api-php": "^0.1.0",
		"evernote/evernote-cloud-sdk-php": "dev-master",
		"facebook/php-sdk-v4" : "4.0.*",
		"kdyby/rabbitmq": "^1.1",
		"google/apiclient": "^2.0.0@RC",
		"kdyby/console": "^2.5",
		"mpdf/mpdf": "5.7.2",
		"joseki/pdf-response": ">= 2.1",
		"phpoffice/phpexcel": "1.8.0",
        "dirkgroenen/Pinterest-API-PHP": "0.2.11",
		"php-http/curl-client": "1.5.0",
		"guzzlehttp/psr7": "1.3.1",
		"sparkpost/php-sparkpost": "dev-master",
		"php-http/message": "1.3.1",
		"happyr/linkedin-api-client": "1.0.0",
		"nojimage/twitter-text-php": "1.1.1",
		"stekycz/cronner": "1.0.2",
		"guzzle/http": "3.7.*@dev",
		"php-http/guzzle6-adapter": "^1.1"
	},

**Comment by michalhudecek** [comment]
It seems duplicit to https://github.com/HvyIndustries/crane/issues/137

**Comment by michalhudecek** [comment]
FYI ... it gets stuck on evernote-cloud-sdk-php

**Comment by nevadascout** [comment]
Thanks for the info, I've added this library to #148

**Comment by michalhudecek** [comment]
This would be a great quick workaround: https://github.com/HvyIndustries/crane/issues/77

**Comment by qcol** [comment]
Same in my CodeIgniter project ... 35.6% 799 of 2243 files :(

**Comment by qcol** [comment]
when use ignoredPaths and add more and more paths, indexing runs only some percent more and stops again...

**Comment by bakeiro** [comment]
same for me using opencart, stops at 33%

**Comment by quentinuys** [comment]
The same for Zend framework. Stuck at 9.8% indexing

**Comment by codewp** [comment]
Same for using Wordpress, Stuck at 48% indexing

**Comment by sirgru** [comment]
Same for ProcessWire, stuck at various steps, usually 89% or 98%.

**Comment by nevadascout** [comment]
This should be fixed with the update of php-parser to 2.0.0

**Comment by nevadascout** [comment]
Fixed in v0.3.0
