### ISSUE TITLE
null coalesce not recognized and marked as syntax error

### ISSUE THREAD

**Issue by thomasmoors** [HvyIndustries/crane#179]
When using the null coalesce operator, it will say: syntax error, unexpected ' ?'.
for example:

`$url_operator = $matches[1][0] ?? false;`

**Comment by nevadascout** [comment]
Thanks for reporting this!

@ichiriac looks like more PHP7 functionality that we need to add

**Comment by TheColorRed** [comment]
What version of PHP is installed on your computer? If I am not mistaken vscode uses the linter that is installed on your computer.  I don't think that this is a crane issue.

**Comment by ichiriac** [comment]
@nevadascoot I plan to do it next week, just need to find some time. + fix line/column location bug

The harder part for the release will be  to increase test coverage on lexer (btw actually lexer on master has many fixes vs release 10)

**Comment by nevadascout** [comment]
You're awesome @ichiriac 😄

**Comment by thomasmoors** [comment]
@TheColorRed both XAMPP and MAMP. If it uses path vars as suspected it will be XAMPP running 5,6 by default, so you could be right.

**Comment by TheColorRed** [comment]
@thomasmoors If you have php 7 installed, you can setup the path in your editor settings:

```json
{
    "php.validate.executablePath": "c:\\php\\folder"
}
```

**Comment by TheColorRed** [comment]
@thomasmoors I assume this fixed your issue? If so, @nevadascout I think this could be closed.

**Comment by nevadascout** [comment]
Closing. We can re-open if the issue is not resolved
