### ISSUE TITLE
High cpu usage on spawned process PHP CLI

### ISSUE THREAD

**Issue by isvaljek** [HvyIndustries/crane#185]
As soon as I enable PHP Intellisense it creates a process PHP CLI and it causes the vents on my laptop to start spinning. There is no progress bar or anything that indicates the progress (if any) of file parsing. I tried disabling all other extensions but same thing happens.
The php 7.0.9 is in the path variable and accessible on the command line.

**Comment by nevadascout** [comment]
Crane itself doesn't use the PHP CLI, try disabling VS Code's PHP linter in your settings and see if that helps

**Comment by nevadascout** [comment]
I think you might have the wrong repository, are you using Felix's language server?

https://github.com/felixfbecker/php-language-server
