### ISSUE TITLE
php code inside <script>

### ISSUE THREAD

**Issue by shoxsz** [HvyIndustries/crane#188]
I don't know if this is really a problem but when i use php code inside a script tag, for instance:
````
<script>

<?php?>

</script>
````

the closing tag swap its colors, the `<\` and `>` goes red and the text `script` goes white, haven't reported this with other tags.

**Comment by nevadascout** [comment]
Please report this to the [VS Code repository](https://github.com/microsoft/vscode) as this is not a bug with crane
