### ISSUE TITLE
Performance problems with `qualityOfLife`-feature

### ISSUE THREAD

**Issue by jrieken** [HvyIndustries/crane#190]
We have identified[1] this extension as being responsible for high loads in the "extension host" (the process in which extensions run). The `QualityOfLife`-feature seems to responsible for that, effectively maxing out that process, hindering other extension code from running. My suspect is the `styleTodoComments` and I suggest to make the following changes:

* cap the number of lines you are looking at, like [`i < Math.min(1000, editor.document.lineCount)`](https://github.com/HvyIndustries/crane/blob/master/client/src/features/qualityOfLife.ts#L55), because there might be insanely large documents for which things take too long otherwise
* use `line.range.end` instead of [`99999`](https://github.com/HvyIndustries/crane/blob/master/client/src/features/qualityOfLife.ts#L63), otherwise we have re-compute that information
* last and most importantly **debouncing** and **filtering** is missing [here](https://github.com/HvyIndustries/crane/blob/master/client/src/features/qualityOfLife.ts#L18). In effect, once this extension has been loaded, *every* keystroke in *any* document will kick off the todo-tag logic. 

[1] How do we know? The extension host must send a [ping](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/extensionHost.ts#L123) every 250ms to the main thread. If that doesn't happen 4 times in a row we send a telemetry event containing the ids of all active extensions. Those lists of ids we analyse to find extensions that occur over and over again.

**Comment by jrieken** [comment]
Apart from the perf suggestions in https://github.com/HvyIndustries/crane/issues/190#issue-191747788 you could also move the logic into the server-part of your extensions. That would be the 🏅

**Comment by nevadascout** [comment]
Thanks for this information! We'll try to get this sorted when we can

**Comment by nevadascout** [comment]
This will be released with v0.3.3

Thanks @jrieken for the tips, sorry it took so long to implement them!

**Comment by nevadascout** [comment]
This has now been fixed in v0.3.3
