### ISSUE TITLE
Error to install via composer

### ISSUE THREAD

**Issue by Simplesmente** [HvyIndustries/crane#192]
Hi there, I'm trying install this package via composer, but the tool is throw the following error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for felixfbecker/language-server ^4.0 -> satisfiable by felixfbecker/language-server[v4.0.0].
    - felixfbecker/language-server v4.0.0 requires jetbrains/phpstorm-stubs dev-master -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

Do you can help me ?

**Comment by nevadascout** [comment]
Hi, I think you have the wrong project! Felix's PHP language server is here: https://github.com/felixfbecker/php-language-server

**Comment by Simplesmente** [comment]
Sorry.
