### ISSUE TITLE
High CPU usage on startup

### ISSUE THREAD

**Issue by sjelfull** [HvyIndustries/crane#194]
VS Code version: 1.8.0
OSX: Sierra 10.12.1

I restarted VS Code just now, and on a non-PHP project, I see this in the process list:

![image](https://cloud.githubusercontent.com/assets/10508/21258434/4bedddc4-c37d-11e6-8773-257adacec981.png)

It's currently using 95% CPU without any indication of doing anything, and this is on a project that doesn't contain any PHP code.

Might be related to #185 ?

**Comment by TheColorRed** [comment]
This is for a different PHP Language Server (https://github.com/felixfbecker/php-language-server)

**Comment by sjelfull** [comment]
Oh! Sorry, and thanks, i'll post it there.
