### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by NewFuture** [HvyIndustries/crane#200]
see this

![image](https://cloud.githubusercontent.com/assets/6290356/21705223/8af0e53e-d3f9-11e6-98c0-8eca39f27744.png)

**Comment by Spectrik** [comment]
@nevadascout 

I can confirm that this is happening for me too on my Ubuntu 16 x64

**Comment by nevadascout** [comment]
@Spectrik Thanks for letting us know! We're in the process of rewriting the parser to fix this (and many other problems!)

**Comment by nevadascout** [comment]
Fixed in v0.3.0
