### ISSUE TITLE
Not working in Folders which includes '+' character.

### ISSUE THREAD

**Issue by BladeMight** [HvyIndustries/crane#203]
Intellisense stops working on directories which names have special chars such as **+**.
**upd**: 
Also Intellisense **randomly** stops working, and I can't do anything about it. (only creating new vscode profile solves it)

**Comment by ichiriac** [comment]
Hi @BladeMight,

The problem with `+` symbol in path names may be resolved from the last release 0.3.4. Here more details on the bugfix : https://github.com/HvyIndustries/crane/issues/257#issuecomment-287885384

Can try to update and tell us if it solves your problems ?

**Comment by BladeMight** [comment]
@ichiriac Yup, it works.
