### ISSUE TITLE
Not working with older versions of PHP (5.3)

### ISSUE THREAD

**Issue by irreverencieux** [HvyIndustries/crane#206]
Not working with older versions of PHP (5.3). My hosting is GoDaddy and they aren't supposed to upgrade their php version just because of me. 😝

**Comment by nevadascout** [comment]
Please can you let me know what exactly isn't working?

I am using Crane with 5.3 and I haven't noticed any (obvious) problems with it!

**Comment by TheColorRed** [comment]
You could upgrade your local commandline php version, and keep your local server version at 5.3...

**Comment by irreverencieux** [comment]
*Ups!*

I apologize for the mistake. I rechecked again and the bug is in another
php intellisense plugin (the Felix Becker one), not Crane.


*Orlando Gómez *
