### ISSUE TITLE
No class-level suggestions being shown

### ISSUE THREAD

**Issue by Kcko** [HvyIndustries/crane#21]
Instead of words ( Is it necessary to enable indexing or something for correct behavior?)

![](http://files.rjwebdesign.cz/i/20160411-215005.png)

In class file i expect member metods
 and variables instead of native PHP functions ...

**Comment by nevadascout** [comment]
The PHP functions and variables being suggested is built-in functionality of VS Code that I can't currently disable.

I realised recently if you have any namespaces in your code you won't get any calculated suggestions at all (see #7). This is probably the problem you have here.

Rest assured that getting this working is my top priority for version 0.1.6 (next release)

**Comment by nevadascout** [comment]
@Kcko This should now be fixed in the latest update (v0.1.6)! :+1:
