### ISSUE TITLE
Intellisense error after "+="

### ISSUE THREAD

**Issue by guang-zhang** [HvyIndustries/crane#210]
when tapping following code,i get some errors.
`$b = 0;`
`$a += $b;`
`$`

[Error - 下午1:18:12] Request textDocument/completion failed.
  Message: ErrorException: Undefined property: PhpParser\Node\Expr\AssignOp\Plus::$left in C:\Users\ASUS\.vscode\extensions\felixfbecker.php-intellisense-1.1.1\vendor\felixfbecker\language-server\src\DefinitionResolver.php:589
Stack trace:
#0 C:\Users\ASUS\.vscode\extensions\felixfbecker.php-intellisense-1.1.1\vendor\felixfbecker\language-server\src\DefinitionResolver.php(589): {closure}(8, 'Undefined prope...', 'C:\\Users\\ASUS\\....', 589, Array)
#1 C:\Users\ASUS\.vscode\extensions\felixfbecker.php-intellisense-1.1.1\vendor\felixfbecker\language-server\src\DefinitionResolver.php(796): LanguageServer\DefinitionResolver->resolveExpressionNodeToType(Object(PhpParser\Node\Expr\AssignOp\Plus))
#2 C:\Users\ASUS\.vscode\extensions\felixfbecker.php-intellisense-1.1.1\vendor\felixfbecker\language-server\src\CompletionProvider.php(274): LanguageServer\DefinitionResolver->getTypeFromNode(Object(PhpParser\Node\Expr\AssignOp\Plus))
#3 C:\Users\ASUS\.vscode\extensions\felixfbecker.php-intellisense-1.1.1\vendor\felixfbecker\language-server\src\Server\TextDocument.php(362): LanguageServer\CompletionProvider->provideCompletion(Object(LanguageServer\PhpDocument), Object(LanguageServer\Protocol\Position))
#4 [internal function]: LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}()
#5 C:\Users\ASUS\.vscode\extensions\felixfbecker.php-intellisense-1.1.1\vendor\sabre\event\lib\coroutine.php(70): Generator->send(Object(LanguageServer\PhpDocument))
#6 C:\Users\ASUS\.vscode\extensions\felixfbecker.php-intellisense-1.1.1\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(Object(LanguageServer\PhpDocument))
#7 C:\Users\ASUS\.vscode\extensions\felixfbecker.php-intellisense-1.1.1\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#8 C:\Users\ASUS\.vscode\extensions\felixfbecker.php-intellisense-1.1.1\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#9 C:\Users\ASUS\.vscode\extensions\felixfbecker.php-intellisense-1.1.1\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#10 C:\Users\ASUS\.vscode\extensions\felixfbecker.php-intellisense-1.1.1\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#11 C:\Users\ASUS\.vscode\extensions\felixfbecker.php-intellisense-1.1.1\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#12 {main}
  Code: -32603

**Comment by ichiriac** [comment]
Hi @guang-zhang,

As you can see from the error stack issue comes from another extension `extensions\felixfbecker.php-intellisense-1.1.1`.

Maybe we could with the next release warn users with potential errors from others PHP extensions and show them how to disable.

**Comment by guang-zhang** [comment]
Oh,so i'm in the wrong places.Thanks.
