### ISSUE TITLE
Suggest namespaces and in scope classes in "use" statements

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#223]
When typing `use` statements at the top of files, we should suggest **ONLY** namespaces and classes within that namespace

```php

use Namespace\Something\Class;
use 
//  ^ suggestions here for namespaces and classes only

```

**Comment by ichiriac** [comment]
Hi @nevadascout ,

PHP7 introduced also `function` and `const` keywords. 

Here an example of valid syntax :

PHP Script :
```php
<?php
use bar\baz as barBaz, 
    baz\boo as bazBoo
;
use Company\Baz  {
    Foo as FooAlias,
    Bar as BarAlias
};
use const Compagny\Foo\BAR_VALUE;
use function Compagny\Foo\Bar as FooBar;
```

**Comment by nevadascout** [comment]
Core functionality added in v0.3.1.

New tasks created for multi-line use statements and PHP7 syntax: #235 #242
