### ISSUE TITLE
Triggering a re-index while an index in progress sometimes causes progress to go past 100%

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#245]
If an index of a project is in progress and the user re-triggers another index (crtl+shift+r), then the progress can go past 100% and it may never complete.

![screen shot 2017-03-06 at 09 04 33](https://cloud.githubusercontent.com/assets/377089/23703555/70eb4d80-03f8-11e7-9b7e-75776627ad7e.png)

Note both the file count and progress percent are incorrect in the above screenshot

**Comment by ichiriac** [comment]
I've fixed this issue by using a flag during indexing - seems to fix this bug

**Comment by nevadascout** [comment]
Released in v0.3.5
