### ISSUE TITLE
Cant upgrade from .022

### ISSUE THREAD

**Issue by mybigman** [HvyIndustries/crane#254]
Hi,

VSCode shows I can update it, click update (no errors) hit reload and it still shows .022 with the update flag next to it.

Thanks

**Comment by nevadascout** [comment]
Can you try uninstalling the plugin, restarting VS Code, then trying to install it from the marketplace?

You may want to ask this question or report a bug on the [vscode repository](https://github.com/Microsoft/vscode/issues) as the plugin updates are not something that we have direct control over.

**Comment by mybigman** [comment]
Hi...

I uninstalled and reinstalled, even though it showed the latest version for installing it only installed .22 and shows the update marker again.

Thanks.

**Comment by nevadascout** [comment]
Hi @mybigman that's really odd. This sounds like a vscode bug, so you might want to report it to them!

**Comment by TheColorRed** [comment]
@mybigman  I have had this issue, what yo need to do is find your plugins directory. On Windows it is located here: `$HOME/.vscode/extensions/`

Next you need to find the folder(s) prefixed with `HvyIndustries` and delete them. You should then be able to re-install Crane.

**Comment by mybigman** [comment]
@TheColorRed - thanks but was a no go.

I upgrade VSC from 1.7.1 to 1.10 and problem is resolved.

Thanks
