### ISSUE TITLE
VS Code freezes and crashes for no reason

### ISSUE THREAD

**Issue by zero2000** [HvyIndustries/crane#26]
bug   hello , lower the extension and makes the visual studio code freezes and restarts all the time .. I was interested in trying it but in the end for those problems and everything worked uninstall normal again. Should check that mistake because it is very annoying and frustrating when programming in php

**Comment by nevadascout** [comment]
Sorry you've had this experience, if you can answer some questions for me that'll be a huge help:

* Which OS are you running VS Code on?
* How big is the PHP project you're working on? (How many files?)
* What are your computer specs? (Processor, disk, ram)

Thanks!

**Comment by zero2000** [comment]
project size 4.08GB
folder 8.596
files 152.3396

OS: windows 8
disk: 1TB
Ram: 4g

**Comment by nevadascout** [comment]
Looking into this and will attempt a fix with #37
