### ISSUE TITLE
textDocument/completion failed

### ISSUE THREAD

**Issue by rajqiu2016** [HvyIndustries/crane#264]
Platform : win32
VSCode Version : 1.10.2
Crane Version : 0.3.3
---
textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'classes' of undefined
  Code: -32603 

_Please explain here what you intended to do, the expected behaviour, and the observed results or errors._

_In order to help us to fix it, try to explain how to reproduce the error, and give us code samples that can help us to reproduce the same behaviour_

**Comment by nevadascout** [comment]
Thanks for the report, but this appears to be a duplicate of #257 

We're working on it and it should be fixed in the next release.
