### ISSUE TITLE
hmm

### ISSUE THREAD

**Issue by hrushikesh88980** [HvyIndustries/crane#275]
Platform : win32
VSCode Version : 1.10.2
Crane Version : 0.3.4
---

_Please explain here what you intended to do, the expected behaviour, and the observed results or errors._

_In order to help us to fix it, try to explain how to reproduce the error, and give us code samples that can help us to reproduce the same behaviour_

**Comment by ichiriac** [comment]
@hrushikesh88980  WOT M8 ?

**Comment by nevadascout** [comment]
Closing this due to lack of detail. Please let us know if there is a real problem and we can reopen this issue.
