### ISSUE TITLE
Getting error when I type > [Code: -32603]

### ISSUE THREAD

**Issue by vinsonyung** [HvyIndustries/crane#277]
Code: 'gateway_id' =>

When I type >, error occur:

[Error - 11:09:37 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'label' of null
  Code: -32603

**Comment by ichiriac** [comment]
Hi @vinsonyung,

This issue will be fixed in the next release, you can get more retails here https://github.com/HvyIndustries/crane/issues/274.

**Comment by vinsonyung** [comment]
Thank you very much @ichiriac . Just updated and it works.
