### ISSUE TITLE
Cannot read property 'label' of null Code: -32603

### ISSUE THREAD

**Issue by rahularyan** [HvyIndustries/crane#279]
Platform : win32
VSCode Version : 1.10.2
Crane Version : 0.3.4
---
Hello @nevadascout
issue #234 appeared again after last update.

```
  Message: Request textDocument/completion failed with message: 
    Cannot read property 'label' of null
  Code: -32603
```

**Comment by ichiriac** [comment]
Hi @rahularyan,

This issue will be fixed in the next release, you can get more retails here https://github.com/HvyIndustries/crane/issues/274.
