### ISSUE TITLE
phpmd: Unable to locate phpmd. Please add phpmd in your global or project local using composer.

### ISSUE THREAD

**Issue by skywalker89** [HvyIndustries/crane#289]
Platform : win32
VSCode Version : 1.10.2
Crane Version : 0.3.6
---
phpmd: Unable to locate phpmd. Please add phpmd in your global or project local using composer.

cant delete 

no idea how to fix this 

_Please explain here what you intended to do, the expected behaviour, and the observed results or errors._

_In order to help us to fix it, try to explain how to reproduce the error, and give us code samples that can help us to reproduce the same behaviour_

**Comment by ichiriac** [comment]
Hi @skywalker89.

Not sure what extensions you are using, but it may be related to this issue : https://github.com/ly95/vsc.phpmd/issues/13

If you need phpmd you may be install it using composer, or you can disable the phpmd extension for the current workspace.

**Comment by skywalker89** [comment]
Hi @ichiriac,
thank you so much-.... am starting with VS Code, so not really sure what I do...

yes, ly95/vsc.phpmd#13 looks very similar... seems there was no solution so far

I for now deinstall phpmd  ... 

Thx a million

Dan
