### ISSUE TITLE
VCode said me that: found a PHP Intellisence Bug?

### ISSUE THREAD

**Issue by misidore** [HvyIndustries/crane#292]
Platform : win32
VSCode Version : 1.10.2
Crane Version : 0.3.6
---

_Please explain here what you intended to do, the expected behaviour, and the observed results or errors._

_In order to help us to fix it, try to explain how to reproduce the error, and give us code samples that can help us to reproduce the same behaviour_

**Comment by ichiriac** [comment]
@misidore :smile: you have just clicked because it was intriguing ? 

Seriously, you find out what kind of bug ?

**Comment by TheColorRed** [comment]
I don't think he found a bug I think he just misunderstood what the button is for. I think many people are confused as to what that button is for. I think many people think that it is reporting to them that the software has found a bug within itself and that they should report it.

**Comment by nevadascout** [comment]
Closing this due to lack of detail. Please let us know if there is a real problem and we can reopen this issue.
