### ISSUE TITLE
Support phpdoc @var tag

### ISSUE THREAD

**Issue by nrip-monotype** [HvyIndustries/crane#297]
Support [@var](https://phpdoc.org/docs/latest/references/phpdoc/tags/var.html) tag. 

- Should be able to list member suggestion on variables using `@var` tag using the `Type` information.

**Comment by seekwe** [comment]
+1

**Comment by nevadascout** [comment]
This is planned for an upcoming release!

https://github.com/HvyIndustries/crane/issues/12

**Comment by nevadascout** [comment]
Closing this as duplicate
