### ISSUE TITLE
can not debug php 

### ISSUE THREAD

**Issue by nhesoktheara** [HvyIndustries/crane#299]
Platform : win32
VSCode Version : 1.11.1
Crane Version : 0.3.6
---

_Please explain here what you intended to do, the expected behaviour, and the observed results or errors._

_In order to help us to fix it, try to explain how to reproduce the error, and give us code samples that can help us to reproduce the same behaviour_

**Comment by nevadascout** [comment]
Please provide more information about the problem you are having

**Comment by nhesoktheara** [comment]
how to install nginx on window and config with php ?

**Comment by nevadascout** [comment]
This is not something that Crane can do.

You'd need to look into installing [xDebug](https://xdebug.org/) to do this.

**Comment by nhesoktheara** [comment]
yes, I want to know xDebug and install Nginx on the window. 
1. How to config xDebug with PHP?
2. How to install Nginx on the window?
