### ISSUE TITLE
VSCode Php Language Server issues

### ISSUE THREAD

**Issue by 78juli** [HvyIndustries/crane#302]
Platform : win32
VSCode Version : 1.11.2
Crane Version : 0.3.6
---
VSCode keeps parsing all php files in the folder I open. Which sometimes causes VSCode to crash. I don't want to parse 1000s of php files in the background. So I'd love to be able to disable that. Here is a screenshot, it's parsing wordpress core files which I really don't need to look into when I'm working on specific theme files only.

![image](https://cloud.githubusercontent.com/assets/3801084/25063151/0f0bc83a-21dd-11e7-85e3-7afa97d2f905.png)

**Comment by nevadascout** [comment]
Hey, the PHP Language Server is not part of the Crane plugin.

It looks like you might have another PHP code completion plugin installed as well...?
