### ISSUE TITLE
Problem writting opening tags

### ISSUE THREAD

**Issue by Robouste** [HvyIndustries/crane#307]
Platform : win32
VSCode Version : 1.11.2
Crane Version : 0.3.6
---

When typing openning tag, intellisense pop up. If we then press enter, it writes something like : 

`<?php_ini_loaded_file()`

![image](https://cloud.githubusercontent.com/assets/5463032/25339110/daca9eb2-2901-11e7-9712-f4aa25e1ee56.png)

`php.suggest.basic` set to false in user settings

**Comment by nevadascout** [comment]
Add `<?php` as an autocompletion item

**Comment by nevadascout** [comment]
Resolved in v0.3.7
