### ISSUE TITLE
popup a message: Neither a pharPath or use of Composer was specified. Aborting...

### ISSUE THREAD

**Issue by fanshengshuai** [HvyIndustries/crane#310]
hi, 
my project does not use Composer, but popup a message on the top.
And it always appear again when i click the close button.
I have lookup the plugin setup option and find nothing about pharPath and Composer or something.
how can  fix it ?

**Comment by fanshengshuai** [comment]
Sorry, the message come from another plugin

**Comment by rafappelt** [comment]
Hi fanshengshuai,
I'm facing the same problem. Could you tell me which plugin was causing the problem?
Thanks

**Comment by ichiriac** [comment]
Hi, seems to be this issue : https://github.com/Dickurt/vscode-php-formatter/issues/17
