### ISSUE TITLE
Usage with ephemeral docker container

### ISSUE THREAD

**Issue by bddenhartog** [HvyIndustries/crane#312]
I've tried a few different ways of using this extension with `Docker`, to no avail:

#### docker command as executablePath

```javascript
{
    "php.validate.executablePath": "docker run -it --rm php:7.1.4-fpm-alpine php",
}
```

#### custom script in PATH

```sh
#!/usr/bin/env sh

docker run -it --rm php:7.1.4-fpm-alpine php "$@"
```

```javascript
{
    "php.validate.executablePath": "php",
}
```

Both generate the `Error spawning PHP: Command failed: php --version` message when opening a `.php` file in VSCode.

Is it possible to use an ephemeral docker container as my "php executable" with this extension?

**Comment by nevadascout** [comment]
Crane doesn't require a PHP executable to run so I think you've talking about a different extension!

**Comment by bddenhartog** [comment]
Hm - that's really odd. You're correct, but I arrived at this repo from within the other extension's settings menu. That seems to be resolved, so, until we meet again!
