### ISSUE TITLE
whats happen,IDE just report "found a php intellisense bug?"

### ISSUE THREAD

**Issue by Ethan19** [HvyIndustries/crane#317]
Platform : win32
VSCode Version : 1.12.2
Crane Version : 0.3.6
---

_Please explain here what you intended to do, the expected behaviour, and the observed results or errors._

_In order to help us to fix it, try to explain how to reproduce the error, and give us code samples that can help us to reproduce the same behaviour_

**Comment by nevadascout** [comment]
Hey, there's no actual bug. It's just a link to follow if you do find a bug
