### ISSUE TITLE
have some suggestion on variables completion.

### ISSUE THREAD

**Issue by YuSuu** [HvyIndustries/crane#32]
1. when  complete the variables name i often need to type a "$" first to do that,i think this can be improved.
2. Inside a class,for example here is a variable $date, if i type "$this->" ,there wont be "date".instead,when i also type a "$" first,"$date" comes . lol...
3. im  a php beginner,and now im learning a framework called Phalcon,i copied the source code of phalcon to the workspace,and i found this Extension can identify some classes, but some functions inside those classes cant support well...On the other hand ,if i imported those source code in Eclipse,it can Autocomplete very well. anyway ,better nothing.haha...

anyway~~thanks 4 ur effort.hope this extension can be better and better

**Comment by nevadascout** [comment]
Hi, thanks for the feedback!

1. PHP Variables always start with a `$`, so it makes sense to suggest them when you type one. If you want a list of suggestions without typing `$`, just press `ctrl + space` to trigger the list.
2. If you have a property called `$date` inside a class, then typing `$this->` should suggest `$date` to you. The property shouldn't be suggested when typing `$`. I'll double check this later, as this may well be a bug :)
3. This extension currently doesn't work well with any namespaced code. This is top of my list to fix for the next release.
