### ISSUE TITLE
PHP syntax crashed

### ISSUE THREAD

**Issue by tutkun** [HvyIndustries/crane#326]
Platform : darwin
VSCode Version : 1.12.2
Crane Version : 0.3.6
---

Hi, my code is valid. But, it show me this error:
http://imgur.com/a/ViXCX

**Comment by TheColorRed** [comment]
This error comes from the PHP linter.  This isn't a crane issue. You're probably missing a semicolon before the comment. But we can't tell because you didn't post the code that is above the comments.

**Comment by nevadascout** [comment]
Closing due to not Crane related
