### ISSUE TITLE
ERRO

### ISSUE THREAD

**Issue by Jeffbreno** [HvyIndustries/crane#334]
[Error - 08:51:08] Server initialization failed.
  Message: UnexpectedValueException: RecursiveDirectoryIterator::__construct(c:/Users/JEFFBR~1\AppData\Local\Temp\jds15582125.tmp,c:/Users/JEFFBR~1\AppData\Local\Temp\jds15582125.tmp): Acesso negado. (code: 5) in C:\Users\jeffbreno\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php:43
Stack trace:
#0 C:\Users\jeffbreno\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(43): RecursiveDirectoryIterator->__construct('c:/Users/JEFFBR...', 4128)
#1 C:\Users\jeffbreno\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(55): Webmozart\Glob\Iterator\RecursiveDirectoryIterator->__construct('c:/Users/JEFFBR...', 4128)
#2 [internal function]: Webmozart\Glob\Iterator\RecursiveDirectoryIterator->getChildren()
#3 C:\Users\jeffbreno\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\webmozart\glob\src\Iterator\RegexFilterIterator.php(130): FilterIterator->next()
#4 [internal function]: Webmozart\Glob\Iterator\RegexFilterIterator->next()
#5 C:\Users\jeffbreno\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\felixfbecker\language-server\src\FilesFinder\FileSystemFilesFinder.php(24): IteratorIterator->next()
#6 [internal function]: LanguageServer\FilesFinder\FileSystemFilesFinder->LanguageServer\FilesFinder\{closure}()
#7 C:\Users\jeffbreno\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\sabre\event\lib\coroutine.php(70): Generator->send(NULL)
#8 C:\Users\jeffbreno\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(NULL)
#9 C:\Users\jeffbreno\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#10 C:\Users\jeffbreno\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#11 C:\Users\jeffbreno\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#12 C:\Users\jeffbreno\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#13 C:\Users\jeffbreno\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#14 {main}
  Code: -32603

**Comment by TheColorRed** [comment]
This is for a different extension.

https://github.com/felixfbecker/vscode-php-intellisense
