### ISSUE TITLE
The language server needs at least PHP 7 installed. Version found: 5.6.30

### ISSUE THREAD

**Issue by davidshangyin** [HvyIndustries/crane#335]
Platform : darwin
VSCode Version : 1.13.1
Crane Version : 0.3.6
---
The language server needs at least PHP 7 installed. Version found: 5.6.30

**Comment by davidshangyin** [comment]
my   setting   ：

  "php.executablePath": "/usr/bin/php",
    "php.suggest.basic": false


my  php version is   php7

**Comment by nevadascout** [comment]
Hi, Crane does not require PHP to be installed to function. I think you've got a problem with another extension.
