### ISSUE TITLE
Language server parsing error

### ISSUE THREAD

**Issue by akpankit** [HvyIndustries/crane#339]
Platform : darwin
VSCode Version : 1.13.1
Crane Version : 0.3.6
---

Language server parsing files and ran into the following extension error.

`[Error - 11:27:02 AM] Request textDocument/completion failed.
  Message: TypeError: strpos() expects parameter 1 to be string, null given in /Users/ankit/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/felixfbecker/language-server/src/CompletionProvider.php:495
Stack trace:
#0 /Users/ankit/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/felixfbecker/language-server/src/CompletionProvider.php(495): strpos(NULL, 'name_parts')
#1 /Users/ankit/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/felixfbecker/language-server/src/CompletionProvider.php(482): LanguageServer\CompletionProvider->isAssignmentToVariableWithPrefix(Object(Microsoft\PhpParser\Node\Expression\AssignmentExpression), 'name_parts')
#2 /Users/ankit/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/felixfbecker/language-server/src/CompletionProvider.php(429): LanguageServer\CompletionProvider->findVariableDefinitionsInNode(Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement), 'name_parts')
#3 /Users/ankit/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/felixfbecker/language-server/src/CompletionProvider.php(179): LanguageServer\CompletionProvider->suggestVariablesAtNode(Object(Microsoft\PhpParser\Node\Expression\Variable), 'name_parts')
#4 /Users/ankit/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/felixfbecker/language-server/src/Server/TextDocument.php(358): LanguageServer\CompletionProvider->provideCompletion(Object(LanguageServer\PhpDocument), Object(LanguageServer\Protocol\Position))
#5 [internal function]: LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}()
#6 /Users/ankit/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/sabre/event/lib/coroutine.php(70): Generator->send(Object(LanguageServer\PhpDocument))
#7 /Users/ankit/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/sabre/event/lib/Promise.php(242): Sabre\Event\{closure}(Object(LanguageServer\PhpDocument))
#8 /Users/ankit/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#9 /Users/ankit/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#10 /Users/ankit/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#11 /Users/ankit/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#12 /Users/ankit/.vscode/extensions/felixfbecker.php-intellisense-1.4.3/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#13 {main}
  Code: -32603 `

**Comment by TheColorRed** [comment]
This error comes from a different extension: https://github.com/felixfbecker/vscode-php-intellisense
