### ISSUE TITLE
Private properties not being suggested with $this

### ISSUE THREAD

**Issue by thamathar** [HvyIndustries/crane#34]
Hey guys, when using $this, the Intellisence not geting the private variables of the class

**Comment by nevadascout** [comment]
Can you give us a code sample please?

An overview showing the private properties, and where you're trying to access them would be great, thanks!

**Comment by thamathar** [comment]
`<?php
ini_set('display_errors',1);
error_reporting(E_ALL);

class ConnectionDB
{

	private $dbhost = "localhost";
	private $dbuser = "user";
	private $dbpass = "pass";
	private $dbname = "dbname";
	/** @var PDO */
	public $conn;
	
	public function openDbConnection()
	{
		try
		{
			$this->dbhost;
			$this->conn = new PDO("mysql:host=$this->dbhost;dbname=$this->dbname", $this->dbuser, $this->dbpass, array(PDO::MYSQL_ATTR_INIT_COMMAND =>  "SET NAMES 'UTF8'"));
			$this->conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
		}
		catch(PDOException $e)
		{
			echo $e->getMessage();
		}
	}

	public function closeDbConnection()
	{
		try
		{
			$this->conn = NULL;
		}
		catch(PDOException $e)
		{
			echo $e->getMessage();
		}
	}
}`

On the $this->dbhost; if I type $this-> just show the public functions/variables, the private ones they don't show.

Would like to add that the PDO stuff doesn't show either, wanted to leave phpstorm to visual studio code, for example, the $e->getMessage(); I must type it manualy.

This code was made on the PhpStorm, was just testing the intellisense properly to move my project from php storm to visual studio code

**Comment by nevadascout** [comment]
That's strange, those private properties should be showing up. I'll have to check what's going on a little later.

I'm aware of the PDO not having any suggestions - it's on my list (see #35 and #36)!

Right now I want to get the Intellisense reliability to be rock solid, then I'll start on these extra features.

Out of curiosity, why don't you want to use PHPStorm any more?

**Comment by thamathar** [comment]
Allways like the Visual Studio, but for PHP doesn't have support on sort of speak, I did found the PhpStorm, its a good IDE but I prever Visual Studio.

Visual Studio Code reminds me alot of Visual Studio, it will have suport for PHP, by extensions done by the community, have a GIT interface alot better then the PhpStorm so its time to move to Visual Studio Code.

**Comment by nevadascout** [comment]
There are actually two extensions for Visual Studio that provide PHP support (both paid) - [VS.PHP](https://www.vsphp.com/) (think it's dead though) and [Devsense](http://www.devsense.com/).

**Comment by nevadascout** [comment]
I've copied your code locally and I can't reproduce your bug - those private properties are being suggested for me fine.

![](http://i.imgur.com/Jtk4jMi.png)

I didn't get any suggestions inside the string for the PDO constructor though - is that what you mean?

**Comment by thamathar** [comment]
Don't know then, in here doesn't show :/

[http://i.imgur.com/6MyffWt.png](url)

**Comment by nevadascout** [comment]
Can you send me a screenshot of what appears when you type the final `>` in `$this->`?

Does it open automatically, or are you pressing `ctrl + space` manually to trigger suggestions?

**Comment by thamathar** [comment]
I did on the previous reply, but it opens automatically

**Comment by nevadascout** [comment]
Hmm, that's very odd. Is that code sample the whole file or is there other code not shown?

**Comment by thamathar** [comment]
The whole file is on my second reply but if needed I can post it again.

If needed I can try to reinstall the VSCode and the ext that I have

**Comment by nevadascout** [comment]
Okay, well I'm going to release a new version of Crane either tonight or tomorrow, so try updating to that when it comes out and let me know if that works any better. I'll let you know when it's out :)

**Comment by thamathar** [comment]
Okidoki thanks, when the update is release let me know to update it also and give u the feedback if its working :D

**Comment by nevadascout** [comment]
Will do! :)

**Comment by nevadascout** [comment]
@thamathar v0.1.6 is now released, so try updating to that and see if it works any better :+1:

**Comment by thamathar** [comment]
Just updated and the problem persiste :/

If you want I can tell you what extesions that I have installed, and if needed I can uninstall the Extensions and leave yours installed to see if the problem persiste.

Is there a way to debug this?

**Comment by nevadascout** [comment]
Are you getting any suggestions, or is it just private properties?

**Comment by thamathar** [comment]
After I type the $this-> I must bring it manually since it wont show automatically.

When I bring manually it just show the public functions (if I type their names) but if I won't type anything shows me everything

**Comment by nevadascout** [comment]
Can you show me a screenshot with the public properties being suggested in it please?

**Comment by thamathar** [comment]
Sure np, if you want I can stream this and talk over TS if needed to try to figur out what is the problem in here

**Comment by nevadascout** [comment]
That might be useful. Do you have Skype? I'm `ShotgunPsycho` on there.

If you're able to send me a copy of the whole PHP project, I can try to reproduce it on my end

**Comment by thamathar** [comment]
Okidoki np, at the moment only have the coreDB.php on the visual studio (was trying to add the Intellisence and such to VSCore before passing everything over).

There are 2 ShotgunPsycho, one on the US and another on UK, witch one are you? My name is António Reis (I belive its the one that will show, since I haven't use skype for quite some time)

**Comment by nevadascout** [comment]
I'm the one in the UK. I'm at work at the moment, so it'll be a few hours before I can take a proper look.

The screenshot I asked for and the project code would be very helpful though :)

**Comment by thamathar** [comment]
Okidoki no worries just added you on skype.

The code that I have its the one that I put here, its the only file at the moment, since like I explain, was trying to get the Intellisence working and such first before passing all the project files into VSCore, so basically its the coreDB.php only at VSCore at the moment (don't mind that index.html was for a test)

**Comment by nevadascout** [comment]
Ah, okay. Well I'll send you a message a little later and hopefully we can sort this out!

**Comment by thamathar** [comment]
Okidoki no worries, I have it open :D

**Comment by nevadascout** [comment]
After debugging with @thamathar, discovered the issue is caused by using tabs instead of spaces to indent code.

New bug created - #v40 with priority for next release.
