### ISSUE TITLE
VS Code Keeps Warning me about using PHP 5.6 vs Upgrading to 7

### ISSUE THREAD

**Issue by abeeku23** [HvyIndustries/crane#346]
Platform : win32
VSCode Version : 1.14.0
Crane Version : 0.3.6
---

_Please explain here what you intended to do, the expected behaviour, and the observed results or errors._

_In order to help us to fix it, try to explain how to reproduce the error, and give us code samples that can help us to reproduce the same behaviour_

**Comment by nevadascout** [comment]
Crane does not require PHP to be installed, the issue must be with another plugin
