### ISSUE TITLE
Add PDO suggestions

### ISSUE THREAD

**Issue by thamathar** [HvyIndustries/crane#35]
Like the title, when I type PDO it can't find any references to it.

**Comment by nevadascout** [comment]
I'm planning a way to allow users to add their own "type definitions" to allow intellisense for classes other than ones they have written (ie. imported with composer).

PDO will be the first "official" definition that I add.

**Comment by thamathar** [comment]
Thanks just saw this now, ya even on the phpstorm I did have to add /** @var PDO */ at the top of public $conn; (the variable to handle the PDO) for have access to all the PDO stuff

**Comment by nevadascout** [comment]
Resolved in the 0.2 release candidate. You can now add PHP stub files to get suggestions for built in PHP classes and functions.
