### ISSUE TITLE
Does not understand php 7.1 multiple-catch exceptions

### ISSUE THREAD

**Issue by luispabon** [HvyIndustries/crane#361]
Platform : linux
VSCode Version : 1.16.1
Crane Version : 0.3.8
---

Looks like crane gets its panties in a bunch with php 7.1's multi-catch exception handling

![image](https://user-images.githubusercontent.com/6388823/30539055-a00ff918-9c68-11e7-83ca-0f4d00969ea3.png)

See approved RFC:
https://wiki.php.net/rfc/multiple-catch

**Comment by nevadascout** [comment]
These errors are not from Crane, but likely from a php linter. Do you have one installed?
