### ISSUE TITLE
What the font name of first screenshot?

### ISSUE THREAD

**Issue by richellyitalo** [HvyIndustries/crane#380]
What's font-family of first screenshot?
https://camo.githubusercontent.com/0f5e9dab5cd86ca5733425a2fa5a5f1151ddc603/68747470733a2f2f692
e696d6775722e636f6d2f61396a335639752e676966

**Comment by nevadascout** [comment]
It's FiraCode (https://github.com/tonsky/FiraCode) 😀

**Comment by richellyitalo** [comment]
Thanks!
