### ISSUE TITLE
vscode engine version set too high

### ISSUE THREAD

**Issue by bchanudet** [HvyIndustries/crane#41]
Hello again,

I was trying to play a little with your newest version, so I forked the repo and tried it. VSCode gave me an error on all lines `import {...} from 'vscode';`, and refused to run for debugging.

I figured out that your version requirement of the vscode engine is a little too high (0.11.x doesn't exist yet), so the vscode module doesn't download the vscode typings definition. 

Going back to 0.10.x and redo a `npm install vscode` fixed the problem, and I was able to run the extension with my modifications.

Hope this helps,

Cheers

**Comment by nevadascout** [comment]
Thanks for letting me know.

I've was fiddling around with the version number as I couldn't get it to work with any version yesterday and forgot to change it back!
