### ISSUE TITLE
Debug option

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#42]
Enable debug mode in user/workspace settings and log everything out to a file.

- [ ] File parsing (success/error)

**Comment by nevadascout** [comment]
Resolved in 749cc081a174f5764da4c356ba289bb5492007c8

**Comment by TheColorRed** [comment]
I made a small change, I put it in a static function, so we don't have to do an `if` everywhere. So it looks like this:

```js
    public static debug(message: string)
    {
        var debugMode: boolean = craneSettings ? craneSettings.get<boolean>("debugMode", false) : false;
        if (debugMode) {
            outputConsole.show();
            outputConsole.appendLine(message);
        }
    }
```

Then just call it from anywhere you have access to the `Crane` class:

```js
Crane.debug('My message');
```

**Comment by nevadascout** [comment]
Cool, send me a pull request and I'll merge this in!
