### ISSUE TITLE
Locks Up Editor

### ISSUE THREAD

**Issue by TheColorRed** [HvyIndustries/crane#43]
I just installed this extension, and ever since my editor has stopped responding. Nothing in particular is causing this, but it is after it "Processes the files" it happens.

Here are the cases that I have had when this happens:

- Typed `$` and it locked
- Went to the bathroom, came back and it was locked

**Comment by TheColorRed** [comment]
I noticed that you are aware of this. Closing.

**Comment by nevadascout** [comment]
Can you give me more information?

- How big is the folder you're opening?
- What are your PC specs?

I've used the extension on several different PCs with various size projects and been unable to reproduce the editor freezing or locking up.

For some large projects it never finishes processing files and thus never gives any suggestions, but that's a separate issue - the editor still works fine

**Comment by TheColorRed** [comment]
I am working with a Laravel project. Here is the folder information:

![capture](https://cloud.githubusercontent.com/assets/1571806/15083328/331ff0c0-1392-11e6-84b9-28ae865aafb7.PNG)

The computer should be powerful enough to handle it. It has:

![capture2](https://cloud.githubusercontent.com/assets/1571806/15083379/7741ecb8-1392-11e6-9d67-c8573b5f7c5f.PNG)

**Comment by nevadascout** [comment]
The largest project I've tested it with has been ~5,000 files and it didn't work very reliably on that so I can see this size of project being an issue. I'll keep it in mind for the future
