### ISSUE TITLE
Clean up the way the current item finds words at the cursor

### ISSUE THREAD

**Issue by TheColorRed** [HvyIndustries/crane#46]
The code is doing a strange validation to get a string to see if it is part of the current class. Workbench has a built in function to get the current word where the cursor is, this could make the code cleaner with smaller if statements. Where this:

```ts
if (expression.lastIndexOf("$this", 0) === 0 ||
    expression.lastIndexOf("($this", 0) === 0 ||
    expression.lastIndexOf("if($this", 0) === 0 ||
    expression.lastIndexOf("elseif($this", 0) === 0 ||
    expression.lastIndexOf("!$this", 0) === 0)
{
```

would become this:

```ts
if(expression == '$this'){
```

**Comment by nevadascout** [comment]
When you say "Workbench", what do you mean?

I know VS Code has a function to get the word under the cursor, but it wasn't available to use on the server

**Comment by TheColorRed** [comment]
You can use it on the client then send a notification to the server.

    this.langClient.sendNotification()

**Comment by nevadascout** [comment]
As of https://github.com/HvyIndustries/crane/pull/67/files#diff-87377fe5c568eb8fd1cdf5c6f241e6ecR274 this is now resolved
