### ISSUE TITLE
TreeBuilder Throwing TypeError. File doesn't get processed.

### ISSUE THREAD

**Issue by TheColorRed** [HvyIndustries/crane#47]
Somewhere in the treeBuilder This is getting thrown:

    [TypeError: Cannot read property '0' of null]

**Comment by TheColorRed** [comment]
Pull Request #48 fixed this by adding an `if` statement around `ProcessBranch` to check for null values before it attempts to process again.

**Comment by nevadascout** [comment]
I've now tweaked this slightly to also check for `undefined` as well as `null` values.
