### ISSUE TITLE
Cache object tree for each project to speed up load times

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#50]
My suggestion is to generate a simple hash of the workspace directory and use that as the folder name in `%APPDATA%` on windows and `~/.crane` on OSX/Linux. For example:

Workspace folder: `C:/users/ns/projects/myproject/`
Generated hash of the folder string: `uef5vbrtfeo8`

Cache folder system:

```
%APPDATA%
    \ crane
       \ uef5vbrtfeo8
         \ tree.cache
       \ nyf9psbtd9rg
         \ tree.cache
```
Each workspace that has something to store in the cache gets a separate folder inside the crane directory to store the cache files in.

This prevents needing to update the gitignore and keeps the workspace folder clean. This is especially important because some git tools update diffs whenever any file in a workspace changes, and if we're constantly modifying cache files then this could cause an issue.

Let's add a new command (Rebuild Sources) -- both a command from the palette and a keyboard shortcut <kbd>Ctrl + Shift + R</kbd> (?)

I also think this should be enabled by default. Using a folder other than the project workspace to store the cache files makes this less of an issue.

**Comment by TheColorRed** [comment]
How will we handle the issue of when someone moves the source code from one place to another?

**Comment by nevadascout** [comment]
I don't think this will happen often enough to become an issue. Worst case scenario, the user can just manually delete the project cache files.

I also just realised the we may have a problem when pulling changes with git - we'll need to rebuild the cache whenever a file in the workspace is changed

**Comment by TheColorRed** [comment]
It looks like this is working properly, It would be nice to get some feedback on this to make sure all is working well (I have not yet integrated the settings). I don't have a mac to test on, so I can't test there, but I do have Linux which I will test on later. Maybe getting rid of the caching on/off setting would be a better idea, just enforce it?

- Rebuild sources: <kbd>Ctrl+Shift+R</kbd>

https://github.com/TheColorRed/crane/tree/optimization-2

**Comment by nevadascout** [comment]
Cool thanks, I'll try this out. I have a mac we can test this on, so I'll do that too.

I'd suggest that we remove the `isProject` setting and create one called `saveCache` instead, which defaults to true. Then we'll always cache the tree unless the user decides to disable it.

Rebuild sources should probably be added to the command palette as well as being a keyboard shortcut (if it's not already)

**Comment by TheColorRed** [comment]
Yeah I have it in the command palette as well

**Comment by TheColorRed** [comment]
When Rebuilding sources, I am having an issue. If you rebuild sources too many times it hangs up. I have added the following to `server/src/server.ts`

```js
    if (project.rebuild) {
        workspaceTree = [];
    }
```

Is there anything else I should be clearing that I am missing?

**Comment by nevadascout** [comment]
I can't think of anything else.

How many times do you run it before it starts hanging? And how frequently are you running it?

**Comment by TheColorRed** [comment]
I am running it 2 times successfully, and the 3rd time is when it crashes at about 80% (2569 files).

**Comment by TheColorRed** [comment]
I tried a larger project with 4525 files, and I can do it 1 time successfully, and the second time it crashes.

**Comment by TheColorRed** [comment]
Okay I think I figured it out. When I turn off debug mode I can do this many times, and I haven't seen it crash yet..

**Comment by TheColorRed** [comment]
I found `outputConsole.dispose();` which says it frees associated resources.
I also found `outputConsole.clear()` which clears the output which seems to be what is taking up the most resources.

So to solve this I created a method that will clear the console and dispose of resources when the sources are rebuilt:

``js
    public static clear() {
        outputConsole.clear();
        outputConsole.dispose();
    }
```

**Comment by nevadascout** [comment]
Awesome, great work!

**Comment by TheColorRed** [comment]
haha I almost thought my optimization was a waste of time :) But looks like all is working on Windows.

On my 4k file project, the sources load in under 1s!

If you or anyone has a larger project I think it would be wise to test this on that project.

**Comment by TheColorRed** [comment]
Tested on Linux, I had to make an adjustment to the `getCraneDir()` method for it to work.

**Comment by nevadascout** [comment]
Cool, I'll test it on OSX as soon as I can

**Comment by TheColorRed** [comment]
https://github.com/TheColorRed/crane/tree/optimization-2

branch: optimization-2

**Comment by TheColorRed** [comment]
Any progress on osx testing?

**Comment by nevadascout** [comment]
Tested and working on OS X 10.11.5 (El Capitan)
