### ISSUE TITLE
Freezing Bug

### ISSUE THREAD

**Issue by MOODVE** [HvyIndustries/crane#52]
I installed this extension to VS CODE, then it started to freeze. And I have to restart VS code every time.
I have this issue with combination of VS 1.1.0 an this extension. It worked perfectly on previous build. Without the extension I don't have any freezing problem.

**Comment by nevadascout** [comment]
Hey @MOODVE, we're aware of this issue and it should be fixed in the next version of Crane (v0.1.8) which should hopefully be released within the next few days
