### ISSUE TITLE
Deleting a file does not remove suggestions

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#53]
If you delete a PHP file after it has been parsed, then the suggestions created from that file remain.

We need to watch the workspace and when a file is deleted, remove it from the tree.

**Comment by TheColorRed** [comment]
We should also watch the workspace for when files are added/modified (git branch change/composer package install) if it is not already doing so...

**Comment by nevadascout** [comment]
Yep, this is a dupe - closing
