### ISSUE TITLE
Remove/Document `ctrl+d` inclusion of key binding for `crane.duplicateLine` command

### ISSUE THREAD

**Issue by panjiesw** [HvyIndustries/crane#57]
Hi,
In linux, this introduce an unexpected surprise as the default command `editor.action.addSelectionToNextFindMatch` is binded to `ctrl+d`.

It would be nice if you'd remove the inclusion of key binding for `crane.duplicateLine` command, or change it to something else, or at least add this key binding inclusion in README.

**Comment by nevadascout** [comment]
Hey, thanks for reporting this.

I'll add an option to disable this keybinding in the settings for the next release.

**Comment by TheColorRed** [comment]
Duplicate line is built into vscode. I think the key binding should be removed altogether...

**Comment by nevadascout** [comment]
Resolved in c7dea58b49d370fca534d83c832b46cd3f6d7e07
