### ISSUE TITLE
Document Symbol Provider

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#6]
VS Code specific feature - when typing `@` in the command palette, we should show a list of symbols available (classes, traits, methods, etc) in the current document

**Comment by TheColorRed** [comment]
I have added a symbol provider.

**Comment by TheColorRed** [comment]
This is in PR #115

**Comment by fuzzy76** [comment]
Can't wait for this!

**Comment by nevadascout** [comment]
This is being re-implemented with the updated php-parser in v0.3.3

**Comment by nevadascout** [comment]
This has now been released in v0.3.3
