### ISSUE TITLE
Reports of issues on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#61]
No idea what the actual issue is, but in the reviews on https://marketplace.visualstudio.com/items?itemName=HvyIndustries.crane, someone says it doesn't work on Ubuntu 16.04 LTS

Probably worth a quick test to check it's nothing obvious...

**Comment by TheColorRed** [comment]
I tested my my branch optimization-2 on 16.04 LTS and it was working for me.

**Comment by nevadascout** [comment]
I thought you probably had :)
