### ISSUE TITLE
"Report PHP Intellisense Bug"

### ISSUE THREAD

**Issue by wulftone** [HvyIndustries/crane#63]
I'm on OSX and on any PHP project with this plugin installed it tells me to "Report PHP Intellisense Bug" but I don't see any bug reported.  The plugin doesn't seem to do anything that I can tell at the moment--there's no "Peek definition" or other special features other than the normal word completion.  How can I get more information about what might be going wrong?

**Comment by mattmeye** [comment]
+1

**Comment by TheColorRed** [comment]
Currently auto completion is the only feature available, but as you can see from the README.md, "Peek" and "go to" (https://github.com/HvyIndustries/crane/issues/4) are features that will be coming soon.

**Comment by wulftone** [comment]
Ah, it looked like the only features missing were the bold ones, but it's the entire list! Ok, thanks for clarifying. What's up with the "report bug" in the status bar?

**Comment by TheColorRed** [comment]
That is just a quick link for reporting bugs that you may find.

**Comment by wulftone** [comment]
Ok, it's a bit disconcerting... makes me think that there _is_ a bug. If it said "Click here if you encounter a PHPIntelliSense bug," or something, that'd be clearer. Thanks!

**Comment by nevadascout** [comment]
Thanks for the info! I'll have a look at rewording this to be clearer.

**Comment by nevadascout** [comment]
Resolved in 705b73a06f0bdc1292fb210b4cac844257011581
