### ISSUE TITLE
Issues parsing Smarty library

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#76]
Crane falls over when trying to parse the these two smarty files:

`smarty_internal_template.php`
`smarty_internal_templatebase.php`

No errors are thrown, so this needs further investigation.

**Comment by TheColorRed** [comment]
Is it stopping everything from parsing? We need to find all the `Promise`'s and add a catch to them if they don't have one.

**Comment by nevadascout** [comment]
Yeah, it just dies and never completes - no errors or anything. I'll have a look to see if there are any promises that aren't being fulfilled.

**Comment by nevadascout** [comment]
It seems to actually crash the server thread when this happens, looking into it further

**Comment by nevadascout** [comment]
Resolved in 8d22fc63a2f340ba804deae6b0df8e140b351726
