### ISSUE TITLE
Ability to ignore files for parsing

### ISSUE THREAD

**Issue by nevadascout** [HvyIndustries/crane#77]
Being able to ignore a set of files from parsing would bypass the smarty issues (#76) and would generally be a nice feature.

- [x] Ignore an array of files
- [x] Ignore an array of folders

**Comment by TheColorRed** [comment]
I think this would be a great use of #64 (adding a phpconfig.json).

**Comment by nevadascout** [comment]
Agreed, however I want to add something quickly to go out with this release.

I'll add a new crane setting for this purpose

**Comment by michalhudecek** [comment]
Yes, this would be perfect. It would be a workaround for plenty of bugs with stuck indexing.

**Comment by michalhudecek** [comment]
@nevadascout Wouldn't this be much faster than waiting on update of php-parser?

**Comment by nevadascout** [comment]
@michalhudecek Yes, it would... Adding this to next release!

**Comment by michalhudecek** [comment]
@nevadascout Any ETA for the next release?

**Comment by nevadascout** [comment]
Not sure, a few weeks maybe.

Could create a minor release with this feature in the short term though...

**Comment by michalhudecek** [comment]
That would be great

**Comment by nevadascout** [comment]
Added in the v0.2.2 release

**Comment by michalhudecek** [comment]
@nevadascout Great. Thanks a lot. I tried to use it and set up this in settings:

```
    "crane.ignoredPaths": [
        "/vendor/evernote/*"
    ]
```

But it still gets stuck while indexing Evernote. What am I doing wrong?

![image](https://cloud.githubusercontent.com/assets/1215304/19831917/00662302-9e16-11e6-96ac-2cfca4a65fc1.png)

**Comment by michalhudecek** [comment]
@nevadascout Is there any documentation for the settings for this feature? Am I doing something wrong?

**Comment by TheColorRed** [comment]
@michalhudecek Try this:

```json
 "crane.ignoredPaths": [
        "vendor/evernote/**"
    ]
```

**Comment by nevadascout** [comment]
@michalhudecek Sorry, I saw this but forgot to reply!

As @TheColorRed's code shows, I think it's because you've got a `/` at the start of the path

**Comment by kiatng** [comment]
I am a total noob to vscode. Where do I find _phpconfig.json_ to configure _crane.ignoredPaths_?

**Comment by Nikhil-7** [comment]
I tried both @TheColorRed suggestions but still loading cache folders. Any suggestions ?
