### ISSUE TITLE
Tab in PHP code creates a XML tag

### ISSUE THREAD

**Issue by mrqtsfr** [HvyIndustries/crane#84]
Hi,

when you try to tab in PHP code, automatically creates a XML tag with the text near the cursor.

Thanks.

**Comment by TheColorRed** [comment]
I had this problem last night. But I think it is a vscode issue because I didn't have the extension installed on that instance of vscode.

**Comment by mrqtsfr** [comment]
Ok,

thanks. Do you know if it's possible report this issue to vscode team?

**Comment by nevadascout** [comment]
Hey, I've filed a bug report with the VS Code project here: https://github.com/Microsoft/vscode/issues/7913

**Comment by mrqtsfr** [comment]
Ok, thank you very much, I've wrote my VSCode and OS version in your issue.

**Comment by nevadascout** [comment]
I'm going to close this off as it's a VS Code issue.
