### ISSUE TITLE
Display Crane Version

### ISSUE THREAD

**Issue by TheColorRed** [HvyIndustries/crane#86]
Display Crane version, this should be retrievable from `client/package.json`. 

Here is how TypeScript does it:

![version display](https://cloud.githubusercontent.com/assets/1571806/16208562/6813b2ba-36f8-11e6-903f-b8ac83cbf880.PNG)

**Comment by nevadascout** [comment]
Sounds good. Made one small comment on your PR, then we can get this merged in.

**Comment by nevadascout** [comment]
Resolved in #88
