### ISSUE TITLE
Suggest Functions From Other Files

### ISSUE THREAD

**Issue by TheColorRed** [HvyIndustries/crane#98]
Crane currently does not suggest basic functions (including functions defined in the stubs) in other files than they are defined in.

Take this function for example:

``` php
function println($output) {
    echo $output . PHP_EOL;
}
```

When attempting to use that function in another file, crane does not suggest it as we can see here:

![screenshot from 2016-06-21 20-57-09](https://cloud.githubusercontent.com/assets/1571806/16252318/c5df319e-37f2-11e6-9082-a9b598926e26.png)

**Comment by nevadascout** [comment]
Strange, this exact example works for me on OSX and Windows.

**Comment by TheColorRed** [comment]
I am noticing that this works when it is defined in the same file that it is called from.

If you define it in file `a.php` then attempt to call it in file `b.php` it doesn't get suggested.

**Comment by nevadascout** [comment]
This functionality is currently intentional as we have no way of knowing if a function is in scope in other files.

We need to check the autoloader or the included files to see if it is in scope in other files.

**Comment by nevadascout** [comment]
We probably also need an `isStub` property on the workspace tree so that stubs are always suggested (as users won't be including those files)

**Comment by TheColorRed** [comment]
For now could we just assume that all functions are global? I don't think it happens very often that a function is not a global function...

**Comment by nevadascout** [comment]
Released in v0.3.0
